usr/bin/xtigervncviewer usr/bin
usr/share/applications/xtigervncviewer.desktop      usr/share/applications
usr/share/icons/hicolor/scalable/apps/tigervnc.svg  usr/share/icons/hicolor/scalable/apps
usr/share/icons/hicolor/16x16/apps/tigervnc.png     usr/share/icons/hicolor/16x16/apps
usr/share/icons/hicolor/22x22/apps/tigervnc.png     usr/share/icons/hicolor/22x22/apps
usr/share/icons/hicolor/24x24/apps/tigervnc.png     usr/share/icons/hicolor/24x24/apps
usr/share/icons/hicolor/32x32/apps/tigervnc.png     usr/share/icons/hicolor/32x32/apps
usr/share/icons/hicolor/48x48/apps/tigervnc.png     usr/share/icons/hicolor/48x48/apps
